[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8.0"
pest_derive = "2.8.0"
serde = {version = "1.0.219", featrures = ["derive"]}
serde_json = "1.0.140"
chrono = "0.4.41"
thiserror = "2.0.12"