WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
COMMENT = _{ "#" ~ (!"\n" ~ ANY)* ~ "\n" }

identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_" | " ")* }

property = @{ "__" ~ property_name ~ "__" }
property_name = @{ (!("__") ~ ANY)+ }

label_name = @{(ASCII_ALPHANUMERIC | ".")+}
label_predicate = _{
    "clears"
  | "succeeds"
  | "qualifies"
  | "passes"
  | "meets requirements"
  | "satisfies"
  | "is valid"
  | "is approved"
  | "has passed"
  | "is authorized"
  | "is sanctioned"
  | "is certified"
  | "is permitted"
  | "is legitimate"
  | "is satisfied"
}
label_reference = { ("§" | "$") ~ label_name ~ label_predicate? }

rule_reference = { "the"? ~ object_selector ~ reference_name }
reference_name = @{ (!("." | "\n") ~ ANY)+ }

length_of_expr = { ("the")? ~ "length" ~ "of" ~ property_access }
number_of_expr = { ("the")? ~ "number" ~ "of" ~ property_access }

// Use a non-greedy match that stops at a period or when we see whitespace followed by "if"
outcome = @{ outcome_char+ }
outcome_char = { !("." | (WHITESPACE+ ~ "if" ~ WHITESPACE)) ~ ANY }
